feat: fix phpdoc check, add grouping, trimmed logs, improve testing
- show relevant path (less noise) (phpdoc)
- show only paths that have issues (phpdoc)
- show less boring logs (via grouping)
- add workflow branch options for testing different ci changes (ci)

diff --git a/.github/plugin/setup/action.yml b/.github/plugin/setup/action.yml
--- a/.github/plugin/setup/action.yml
+++ b/.github/plugin/setup/action.yml
@@ -57,22 +57,38 @@ runs:
 
     - name: Initialise moodle-plugin-ci
       run: |
-        composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
+        # Initialise moodle-plugin-ci (install via composer)
+        echo "::group::Initialise moodle-plugin-ci"
+
+        composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci m-ci ^3
         # Add dirs to $PATH
-        echo $(cd ci/bin; pwd) >> $GITHUB_PATH
-        echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
+        echo $(cd m-ci/bin; pwd) >> $GITHUB_PATH
+        echo $(cd m-ci/vendor/bin; pwd) >> $GITHUB_PATH
         # PHPUnit depends on en_AU.UTF-8 locale
         sudo locale-gen en_AU.UTF-8
+
+        echo "::endgroup::"
       shell: bash
 
     - name: Install dependencies
       if: ${{ inputs.extra_plugin_runners }}
       run: |
+        # Install dependencies
+        echo "::group::Install dependencies"
+
         ${{ inputs.extra_plugin_runners }}
+
+        echo "::endgroup::"
       shell: bash
 
     - name: Install Moodle
-      run:  moodle-plugin-ci install -vvv --plugin ./plugin --db-host=127.0.0.1
+      run: |
+        # Install moodle commands
+        echo "::group::Moodle install output"
+
+        moodle-plugin-ci install -vvv --plugin ./plugin --db-host=127.0.0.1
+
+        echo "::endgroup::"
       shell: bash
       env:
         DB: ${{ matrix.database }}
@@ -142,7 +158,40 @@ runs:
       shell: bash
 
     - name: Moodle PHPDoc Checker
-      if: ${{ always() }}
+      if: ${{ always() && inputs.highest_moodle_branch == matrix.moodle-branch }}
       # Run this check and only fail CI if it's on 4.0+ / master
-      run: moodle-plugin-ci phpdoc || !(matrix.moodle-branch == 'MOODLE_400_STABLE' || matrix.moodle-branch == 'master')
+      run: |
+        # phpdoc checks
+
+        # Don't stop on faiures
+        set +e
+
+        # Note this block whilst large, was made so that it can be pasted locally if needed and isn't CI specific
+        # Disclaimer: you'll need to adjust the main command but otherwise the handling of output remains the same.
+        output=`GITHUB_PATH=$GITHUB_PATH moodle-plugin-ci phpdoc`
+        haserrors=$?
+
+        # No errors? Print and return.
+        if [[ $haserrors -eq 0 ]]; then
+          echo "phpdoc checks - OK"
+          exit 0
+        fi
+
+        # Skip incorrect errors/warnings and retain the relevant lines.
+        output=`echo "$output" | grep -v 'Class ( is not documented' | grep -v 'Could not connect to debugging client.'`
+        output=`echo "$output" | grep -B1 'Line'`
+
+        # Filter out github actions paths from the output. It should only
+        # show the path relevant to the files in the plugin repo.
+        # For example:
+        # from /home/runner/work/moodle-tool_dataflows/moodle-tool_dataflows/moodle/admin/tool/dataflows/db/upgrade.php
+        # to   db/upgrade.php at best,
+        # or   admin/tool/dataflows/db/upgrade.php
+        currentdir=$(pwd)
+        if [[ "$output" ]]; then
+          echo "$output" | sed -e "s,$currentdir/,,g" | sed -e "s,^moodle/,,g" | tee $GITHUB_STEP_SUMMARY
+          exit 1
+        fi
+
+        echo "phpdoc checks - OK"
       shell: bash
